Fix strict compiler errors (#200)
* GDAXExchangeAPI: OrderPage contains a OrderInfo[], not a BaseOrderInfo[].

GDAX's API will always return a BaseOrderInfo sub-interface instance,
not a BaseOrderInfo itself.

* OrderbookDiff#generateDiffCommands(): use correct types.

Don't type assert a value to any, get one of its properties and type
assert it with the incorrect type.

* getSubscribedFeeds(): fix error when tsc compiles in strict mode.

src/factories/poloniexFactories.ts(48,64): error TS2345: Argument of type 'typeof PoloniexFeed' is not assignable to parameter of type 'ExchangeFeedConstructor<PoloniexFeed, ExchangeFeedConfig>'.
  Types of parameters 'config' and 'config' are incompatible.
    Type 'ExchangeFeedConfig' is not assignable to type 'PoloniexFeedConfig'.
      Property 'tickerChannel' is missing in type 'ExchangeFeedConfig'.